In [4]:
import csv
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
def spam_number_representation(x):
    if(x=="spam"):
        return 1
    return 0

In [8]:
df['spam']=df['Category'].apply(spam_number_representation)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
df.shape

(5572, 3)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [11]:
X_train.shape

(4457,)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
X_train_cv.shape

(4457, 7721)

In [28]:
v.get_feature_names_out()[7400:7500]

array(['weak', 'weakness', 'weapon', 'wear', 'wearing', 'weasels',
       'weather', 'web', 'webadres', 'webeburnin', 'webpage', 'website',
       'wed', 'weddin', 'wedding', 'weddingfriend', 'wedlunch',
       'wednesday', 'weds', 'wee', 'weed', 'week', 'weekdays', 'weekend',
       'weekends', 'weekly', 'weeks', 'weigh', 'weight', 'weird',
       'weirdest', 'weirdy', 'weiyi', 'welcome', 'welcomes', 'well',
       'welp', 'wen', 'wendy', 'wenever', 'went', 'wenwecan', 'wer',
       'were', 'werebored', 'weren', 'wesley', 'wesleys', 'west',
       'western', 'westlife', 'westonzoyland', 'westshore', 'wet',
       'wetherspoons', 'wewa', 'whassup', 'what', 'whatever', 'whats',
       'whatsup', 'wheat', 'wheel', 'when', 'whenever', 'whenevr',
       'where', 'wherever', 'wherre', 'whether', 'which', 'while',
       'whilltake', 'whispers', 'white', 'whn', 'who', 'whole', 'whom',
       'whore', 'whos', 'whose', 'whr', 'why', 'wi', 'wicket', 'wicklow',
       'wid', 'widelive', 'wif', '

In [15]:
v.get_feature_names_out().shape

(7721,)

In [25]:
v.vocabulary_

{'what': 7457,
 'wearing': 7404,
 'pls': 5239,
 'ask': 1076,
 'macho': 4273,
 'how': 3501,
 'much': 4612,
 'is': 3725,
 'budget': 1534,
 'for': 2917,
 'bb': 1238,
 'bold': 1401,
 'cos': 2007,
 'saw': 5897,
 'new': 4745,
 'one': 4923,
 'lt': 4223,
 'gt': 3236,
 'dollars': 2377,
 'don': 2381,
 'know': 3937,
 'but': 1565,
 'raping': 5548,
 'dudes': 2456,
 'at': 1100,
 'poker': 5271,
 'mila': 4457,
 'age23': 853,
 'blonde': 1381,
 'in': 3624,
 'uk': 7095,
 'look': 4169,
 'sex': 6015,
 'with': 7526,
 'guys': 3256,
 'if': 3583,
 'like': 4085,
 'fun': 3015,
 'me': 4388,
 'text': 6763,
 'mtalk': 4603,
 'to': 6911,
 '69866': 588,
 '18': 313,
 '30pp': 430,
 'txt': 7070,
 '1st': 330,
 '5free': 554,
 '50': 535,
 'increments': 3639,
 'help08718728876': 3380,
 'you': 7684,
 'didn': 2277,
 'hear': 3356,
 'it': 3736,
 'from': 2995,
 'wishing': 7522,
 'beautiful': 1261,
 'day': 2165,
 'each': 2476,
 'moment': 4547,
 'revealing': 5745,
 'even': 2634,
 'more': 4564,
 'things': 6820,
 'keep': 3885,
 'smil

In [19]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
np.where(X_train_np[0]!=0)

(array([7404, 7457], dtype=int64),)

In [33]:
X_train_cv[0]

<1x7721 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [34]:
from sklearn.naive_bayes import MultinomialNB
model= MultinomialNB()
model.fit(X_train_np,y_train)

MultinomialNB()

In [35]:
X_test_cv=v.transform(X_test)

In [36]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       970
           1       0.98      0.95      0.97       145

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [47]:
emails=[
      "hey Swaroop, can we get together to watch footbal game tomorrow?",
     "Reminder for HackWithInfy 2024",
     "Instantly receive ₹400 worth of Bitcoin with SunCrypto",
     "Weekly update for your Quikr Jobs profile",
     "Get covered in seconds",
     "Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!"
]
emails_cv=v.transform(emails)
model.predict(emails_cv)

array([0, 0, 1, 1, 0, 1], dtype=int64)